"""add location and reddit tables

Revision ID: 9d20ab908d8f
Revises: 
Create Date: 2022-11-30 16:56:19.847339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d20ab908d8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.Column('update_date', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_id'), 'location', ['id'], unique=False)
    op.create_table('redditpost',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('op_text', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redditpost_id'), 'redditpost', ['id'], unique=False)
    op.create_table('redditcomment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=256), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('top_comment', sa.String(length=1000), nullable=False),
    sa.Column('replies', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['redditpost.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redditcomment_id'), 'redditcomment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_redditcomment_id'), table_name='redditcomment')
    op.drop_table('redditcomment')
    op.drop_index(op.f('ix_redditpost_id'), table_name='redditpost')
    op.drop_table('redditpost')
    op.drop_index(op.f('ix_location_id'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
